In [3]:
from datetime import datetime
import pandas as pd
import networkx as nx
import json

Metacartel Ventures

First block: 9484668 (Feb-15-2020 01:32:52 AM +UTC)
https://etherscan.io/block/9484668

Other blocks:
10884668 (Sep-18-2020 06:57:11 AM +UTC)

Recent block (for reference): 13316507 (Sep-28-2021 08:58:06 PM +UTC)

summoner: 0x8c8b237bea3c23317d08b73d7137e90cafdf68e6

In [14]:
# Approximate seconds per block

sec_per_block = (datetime(2021, 9, 28, 8, 58, 6) - datetime(2020, 2, 15, 1, 32, 52)).seconds / (13316507 - 9484668)

print("approx. this many blocks per days:", sec_per_block * 86400)
# 86400 seconds per day

# >>> from datetime import datetime
# >>> a = datetime(2011,11,24,0,0,0)
# >>> b = datetime(2011,11,17,23,59,59)
# >>> a-b
# datetime.timedelta(6, 1)
# >>> (a-b).days
# 6

approx. this many blocks per days: 602.3451402838167

In [15]:
9484668 + 602

9485270

In [4]:
# Load data
with open("./data/10884668-results.json", "r") as f:
    results_09182020 = json.load(f)
f.close()

with open("./data/13316507-results.json", "r") as f:
    results_09282021 = json.load(f)
f.close()

In [6]:
df_09182020_members = pd.DataFrame.from_dict(results_09182020["data"]["moloches"][0]["members"])
df_09182020_proposals = pd.DataFrame.from_dict(results_09182020["data"]["moloches"][0]["proposals"])

In [11]:
df_09182020_members["id"][0].split('-')[2]

'0x048acecf7d4eb900a8600bd5caa6bf1a577cacf0'

In [17]:
df_09182020_members["id"] = df_09182020_members.apply(lambda row: row["id"].split('-')[2], axis=1)

In [18]:
df_09182020_members

,createdAt,id,jailed,kicked,loot,shares
0,1602009236,0x048acecf7d4eb900a8600bd5caa6bf1a577cacf0,None,False,0,0
1,1584524154,0x06601571aa9d3e8f5f7cdd5b993192618964bab5,None,False,0,4000
2,1595981957,0x0a09cd09b0107bb98a83f211704f036eca94b92e,None,False,0,0
3,1587695459,0x0aba55c93cf7292f71067b0ba0d8b464592895ca,243,True,0,0
4,1593551488,0x0eabffd8ce94ab2387fc44ba32642af0c58af433,None,False,0,250
...,...,...,...,...,...,...
105,1590508478,0xf9f8c592280533f618993154b7b5a8bcccef49af,None,False,0,0
106,1597997349,0xfafd1d1d502ba454a5fb3d89ede92a45bf8d8d8f,None,False,0,300
107,1613439435,0xfb70222679b5d38fcf555abcb4db0b1f1cc80d1e,None,False,0,0
108,1602183729,0xfdc6a17917115498a3ed417d4a89224685f26ea3,None,False,0,369
109,1605051366,0xff14604575e923ea533eb07f0cb8dee12d15b917,None,False,0,0

In [30]:
print("Number of members:", df_09182020_members["id"].nunique())

Number of members: 110

In [19]:
df_09182020_proposals

,aborted,actions,applicant,cancelled,cancelledAt,createdAt,delegateKey,details,didPass,escrow,...,tributeToken,tributeTokenDecimals,tributeTokenSymbol,uberHausMinionExecuted,votes,votingPeriodEnds,votingPeriodStarts,whitelist,yesShares,yesVotes
0,None,[],0x512e07a093aaa20ba288392eadf03838c7a4e522,False,None,1581731640,0x512e07a093aaa20ba288392eadf03838c7a4e522,VENTURE DAO RISES,True,None,...,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,18,WETH,None,"[{'createdAt': '1582190771', 'id': '0x4570b4fa...",1582349572,1581744772,False,1,1
1,None,[],0x4444444477eb5fe6d1d42e98e97d9c4c03a57f99,True,1589824612,1582350195,0x4444444477eb5fe6d1d42e98e97d9c4c03a57f99,Garrett,False,None,...,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,18,WETH,None,[],0,0,False,0,0
2,None,[],0xe2a82cdccbfa6ebf9817b0c4aed45264bd41fbec,False,None,1582922436,0xe2a82cdccbfa6ebf9817b0c4aed45264bd41fbec,kenny rowe,True,None,...,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,18,WETH,None,"[{'createdAt': '1583449277', 'id': '0x4570b4fa...",1583940772,1583335972,False,1,1
3,None,[],0x865c2f85c9fea1c6ac7f53de07554d68cb92ed88,False,None,1594507874,0x865c2f85c9fea1c6ac7f53de07554d68cb92ed88,"{""id"":""81X6E73Bo"",""title"":""MCV03 Claims tokens...",True,None,...,0x963b06f4565c89b014d616ee01f3a9863004854b,18,MCV03,None,"[{'createdAt': '1594703956', 'id': '0x4570b4fa...",1595122372,1594517572,False,4700,4
4,None,[],0x865c2f85c9fea1c6ac7f53de07554d68cb92ed88,False,None,1594508900,0x865c2f85c9fea1c6ac7f53de07554d68cb92ed88,"{""id"":""rBtdnWfKP"",""title"":""MCV04 claims token ...",True,None,...,0xfb1a5d0ea0df7be649ac969ca9253e875f398990,18,MCV04,None,"[{'createdAt': '1594704017', 'id': '0x4570b4fa...",1595280772,1594675972,False,4700,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,None,[],0xafcd4572408b322ada9890253a7a42a9fa4c2e40,False,None,1594088745,0xcb42ac441fcade3935243ea118701f39aa004486,"{""id"":""aSrZ8IqjG"",""title"":""Callum Ops Payment ...",True,None,...,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,None,None,None,"[{'createdAt': '1594158346', 'id': '0x4570b4fa...",1594704772,1594099972,False,2953,3
395,None,[],0x2a82b65f1a6664967a44cc693dbf006d4dccc063,False,None,1594441881,0x4444444477eb5fe6d1d42e98e97d9c4c03a57f99,"{""id"":""sv4pxalvL"",""title"":""Investment: Pokt.ne...",True,None,...,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,None,None,None,"[{'createdAt': '1594713201', 'id': '0x4570b4fa...",1595057572,1594452772,False,10965,9
396,None,[],0x2a82b65f1a6664967a44cc693dbf006d4dccc063,False,None,1594442095,0x4444444477eb5fe6d1d42e98e97d9c4c03a57f99,"{""id"":""Y-VTIPVRy"",""title"":""Investment: $10k ad...",False,None,...,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,None,None,None,"[{'createdAt': '1594472622', 'id': '0x4570b4fa...",1595064772,1594459972,False,1400,3
397,None,[],0x2a82b65f1a6664967a44cc693dbf006d4dccc063,False,None,1594442274,0x4444444477eb5fe6d1d42e98e97d9c4c03a57f99,"{""id"":""ce8sfGucn"",""title"":""Investment: $10k ad...",False,None,...,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,None,None,None,"[{'createdAt': '1594472701', 'id': '0x4570b4fa...",1595071972,1594467172,False,1400,3
398,None,[],0x0a09cd09b0107bb98a83f211704f036eca94b92e,False,None,1594506980,0xa5c3a513645a9a00cb561fed40438e9dfe0d6a69,"{""id"":""f6E8FR891"",""title"":""Attention Mining wi...",False,None,...,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,None,None,None,"[{'createdAt': '1594657945', 'id': '0x4570b4fa...",1595115172,1594510372,False,1500,3

In [36]:
cols_proposal = ["applicant", "details", "didPass", "lootRequested", "sharesRequested", "aborted", "cancelled", "createdAt", "yesShares", "yesVotes", "noShares", "noVotes", "maxTotalSharesAndLootAtYesVote"]
df_09182020_proposals[cols_proposal]
# df_09182020_proposals.columns

,applicant,details,didPass,lootRequested,sharesRequested,aborted,cancelled,createdAt,yesShares,yesVotes,noShares,noVotes,maxTotalSharesAndLootAtYesVote
0,0x512e07a093aaa20ba288392eadf03838c7a4e522,VENTURE DAO RISES,True,0,1000,None,False,1581731640,1,1,0,0,1
1,0x4444444477eb5fe6d1d42e98e97d9c4c03a57f99,Garrett,False,0,20,None,True,1582350195,0,0,0,0,0
2,0xe2a82cdccbfa6ebf9817b0c4aed45264bd41fbec,kenny rowe,True,0,1320,None,False,1582922436,1,1,0,0,1001
3,0x865c2f85c9fea1c6ac7f53de07554d68cb92ed88,"{""id"":""81X6E73Bo"",""title"":""MCV03 Claims tokens...",True,0,0,None,False,1594507874,4700,4,0,0,41931
4,0x865c2f85c9fea1c6ac7f53de07554d68cb92ed88,"{""id"":""rBtdnWfKP"",""title"":""MCV04 claims token ...",True,0,0,None,False,1594508900,4700,4,0,0,41931
...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,0xafcd4572408b322ada9890253a7a42a9fa4c2e40,"{""id"":""aSrZ8IqjG"",""title"":""Callum Ops Payment ...",True,0,10,None,False,1594088745,2953,3,0,0,38933
395,0x2a82b65f1a6664967a44cc693dbf006d4dccc063,"{""id"":""sv4pxalvL"",""title"":""Investment: Pokt.ne...",True,0,0,None,False,1594441881,10965,9,5030,4,41931
396,0x2a82b65f1a6664967a44cc693dbf006d4dccc063,"{""id"":""Y-VTIPVRy"",""title"":""Investment: $10k ad...",False,0,0,None,False,1594442095,1400,3,5103,4,41931
397,0x2a82b65f1a6664967a44cc693dbf006d4dccc063,"{""id"":""ce8sfGucn"",""title"":""Investment: $10k ad...",False,0,0,None,False,1594442274,1400,3,5030,4,41931
398,0x0a09cd09b0107bb98a83f211704f036eca94b92e,"{""id"":""f6E8FR891"",""title"":""Attention Mining wi...",False,0,0,None,False,1594506980,1500,3,7586,6,38933

In [38]:
df_09182020_members.columns

Index(['createdAt', 'id', 'jailed', 'kicked', 'loot', 'shares'], dtype='object')

In [40]:
df_09182020_member_proposals = pd.merge(df_09182020_members, df_09182020_proposals[cols_proposal], how="left", left_on=["id"], right_on = ["applicant"]).sort_values(["createdAt_y", "applicant"])
df_09182020_member_proposals.head()

,createdAt_x,id,jailed,kicked,loot,shares,applicant,details,didPass,lootRequested,sharesRequested,aborted,cancelled,createdAt_y,yesShares,yesVotes,noShares,noVotes,maxTotalSharesAndLootAtYesVote
93,1582954414,0x512e07a093aaa20ba288392eadf03838c7a4e522,None,False,0,1948,0x512e07a093aaa20ba288392eadf03838c7a4e522,VENTURE DAO RISES,True,0,1000,None,False,1581731640,1,1,0,0,1
85,1591666540,0x4444444477eb5fe6d1d42e98e97d9c4c03a57f99,None,False,0,334,0x4444444477eb5fe6d1d42e98e97d9c4c03a57f99,Garrett,False,0,20,None,True,1582350195,0,0,0,0,0
277,1584501720,0xbf7db386ba18184b91d2b98e13f25ddebc096f1c,None,False,0,1000,0xbf7db386ba18184b91d2b98e13f25ddebc096f1c,Mickael Salabi,True,0,50,None,False,1582430492,1,1,0,0,1001
239,1584502825,0xa0dd8e6c5440a424cd19f5ec30f8fa485e814247,None,False,0,4635,0xa0dd8e6c5440a424cd19f5ec30f8fa485e814247,Number never go down!,True,0,99,None,False,1582470430,1,1,0,0,1001
89,1584459504,0x44c466f3c93c0890e9f3baf33265976a9096b9a3,None,False,0,500,0x44c466f3c93c0890e9f3baf33265976a9096b9a3,Proposal from James Waugh,True,0,50,None,False,1582516458,1,1,0,0,1001

In [49]:

df_09182020_member_proposals[["id", "applicant"]].groupby("id").count()

                                            applicant
id
0x048acecf7d4eb900a8600bd5caa6bf1a577cacf0          1
0x06601571aa9d3e8f5f7cdd5b993192618964bab5          1
0x0a09cd09b0107bb98a83f211704f036eca94b92e          1
0x0aba55c93cf7292f71067b0ba0d8b464592895ca          2
0x0eabffd8ce94ab2387fc44ba32642af0c58af433          1
...                                               ...
0xf9f8c592280533f618993154b7b5a8bcccef49af          3
0xfafd1d1d502ba454a5fb3d89ede92a45bf8d8d8f          1
0xfb70222679b5d38fcf555abcb4db0b1f1cc80d1e          3
0xfdc6a17917115498a3ed417d4a89224685f26ea3          1
0xff14604575e923ea533eb07f0cb8dee12d15b917          4

[110 rows x 1 columns]